### ISSUE TITLE
In mbfuncholding.c, line 185 is there a bug?

### ISSUE THREAD

**Issue by rhino949** [cwalter-at/freemodbus#14]
freemodbus/modbus/functions/mbfuncholding.c;
line 185,  usRegCount = ( USHORT )( pucFrame[MB_PDU_FUNC_READ_REGCNT_OFF + 1] );
like should be: usRegCount |= ( USHORT )( pucFrame[MB_PDU_FUNC_READ_REGCNT_OFF + 1] );

**Comment by JoelStienlet** [comment]
Indeed, I agree this looks like a bug: the 8 upper bits get trashed. The function will sometimes succeed where it should have returned "eStatus = MB_EX_ILLEGAL_DATA_VALUE;"

**Comment by JoelStienlet** [comment]
@cwalter-at can you please make this very small change, just add the "|" at L185?

**Comment by ntfreak** [comment]
see https://github.com/cwalter-at/freemodbus/pull/4/files

**Comment by JoelStienlet** [comment]
So, given the good explanations of karlp on this link, perhaps that first line (L184) could indeed be dropped? The compiler probably drops it anyway (when optimizations are enabled), but that would make the code easier to understand IMO.

**Comment by rhino949** [comment]
I got it.
