### ISSUE TITLE
how can we have dummy values for Input registers in modbus slave ?

### ISSUE THREAD

**Issue by samminen** [cwalter-at/freemodbus#19]
Hi,
   In the modbus slave service, when I read INPUT registers, it always return "0" value for any register. But I want to have some dummy values for these registers by default when slave service come-up.

How can we do this using this library ? Really appreciate for all your help.

**Comment by pvyleta** [comment]
You need to re-implement eMBRegInputCB, see https://github.com/cwalter-at/freemodbus/blob/master/demo/LINUXTCP/demo.c#L219
